### ISSUE TITLE
FR: Specifying Corners to Round x Drop Shadow

### ISSUE THREAD

**Issue by viccalexander** [IcaliaLabs/Presentr#106]
I'm currently rounding the top corners of a view in the following way:

``` swift
override func viewDidLayoutSubviews() {

    // Super
    super.viewDidLayoutSubviews()

    // Round top corners
    view.roundCorners(corners: [.topLeft, .topRight], radius: 8.0)
}

func roundCorners(corners: UIRectCorner, radius: CGFloat) {

    //Create mask layer
    let maskLayer = CAShapeLayer()
    maskLayer.path = UIBezierPath(roundedRect: self.bounds, byRoundingCorners: corners, cornerRadii: CGSize(width: radius, height: radius)).cgPath
    self.layer.mask = maskLayer
}
```

However if I do this to a controller presented with a presentr, the drop shadow property on presentr is ignored (masked). Would be cool to specify which corners we'd want to round and still apply a drop shadow with presentr.

**Comment by danlozano** [comment]
Interesting.

Will look into this, not sure if it's easily done with the way the shadow is handled.

Any ideas?

**Comment by danlozano** [comment]
Hi!

Presentr can't know how masking is going to be handled in the presented view controller.

I just made an update in which presentr never masks/clips the presented view controller's view. So that way, rounded corners & shadows always work.

That way, if you need to mask in your view controller, just add an extra "container view" as the superview to all your other views, and do your masking in that view.

That way, Presentr can happily apply shadows to the real superview.
