### ISSUE TITLE
No fullscreen modal

### ISSUE THREAD

**Issue by tbaranes** [IcaliaLabs/Presentr#17]
Let's say you have an iPad app witch is splitting the screen in two (like multitasking). In the current state of `Presentr`, if I present a viewController on the left side, I will be able to customise my origin and size, but the `PresentrController` frame will still use the screen frame instead of filling only the `presentingViewController` frame.

The result expected would be the same as using `presentedVC.modalPresentationStyle = .OverCurrentContext`. 

I will take a look in the day if I have time, otherwise, I'm really interested in this feature 😄

**Comment by tbaranes** [comment]
I just edited the app example to give a more visual example:

![simulator screen shot 15 jul 2016 09 49 54](https://cloud.githubusercontent.com/assets/1402212/16867352/ac6fd90c-4a71-11e6-978b-b09ca3b3bcb8.png)

![simulator screen shot 15 jul 2016 09 49 56](https://cloud.githubusercontent.com/assets/1402212/16867353/ac908daa-4a71-11e6-8374-28c92e8aedfe.png)

1. Default view when launching app
2. When clicking on "present", it will present an alert, here the issue: I'd like to present only on the yellow and keep the green one clickable

**Comment by tbaranes** [comment]
I look into this, it seems more complicated that I though. In order to have this result, we have to set the `modalPresentationStyle` to `OverCurrentContext`, but `presentationControllerForPresentedViewController` is working only and only if the `modalPresentationStyle` is `Custom`. So right now, I have only one solution in mind
- Don't use anymore `UIPresentationController` and handle all that stuff in it manually using `
UIViewControllerTransitioningDelegate`. Definitely not worth it
- Find a good idea to handle everything together 😆 

I didn't find examples about how to implement that features, but if anyone has a suggestion, I'm interested!

**Comment by danlozano** [comment]
I was about to suggest using a custom PresentationType to set a custom origin/size, but now that I read it I realized that's not the issue. The issue is not the presented view controller itself, but the chrome/background view.

So basically, this issue would appear on ipad when doing multitasking or when doing view controller containment, or like a split view controller.

So, there are two issues, correct?

1. The chrome/background view should only cover the current/presenting view controller.
2. **and** the uncovered view controller **should** be clickable.

The .overCurrentContext is what usually makes the background clickable, right?

Will def. look into this, we can keep discussing it, and implement something as soon as we come up with a solution.

**Comment by tbaranes** [comment]
You did understand right the issue, it's concerning any apps which split the window in different controllers, as you said, that bring to these two issues.

I just watch the WWDC session about PresentationController to have a better understand of how it is working. Following that, we just have to use the right context when presenting the viewController. Normally `shouldPresentInFullscreen` handles this:
- If true, it will use the fullscreen and adapt the view automatically
- If false, it will use the presentingVC context, so keeping the same frame (which will give the right frame to the chrome view, and also make clickable the uncovered view)

So the real question is why `shouldPresentInFullscreen` has no effect on the presentedView 😆 

I pushed the example that I'm using to do my tests, you can find it in my [fork](https://github.com/tbaranes/Presentr/tree/feature/present_over_context).

**Comment by tbaranes** [comment]
For information, I think I misunderstand what's the real purpose of `shouldPresentInFullscreen`. Apparently, it won't change the context of the presentedVC but used to enable or not `UIPresentationController`'s `adaptive*` methods which are used to change the presented content following traits... 

Well, there must be a way to handle this, but it will be for later!

**Comment by gabrielPeart** [comment]
@tbaranes I sent a pull request with this feature. You can try checking my fork.

**Comment by tbaranes** [comment]
I took a quick look on it, I dont think that will introduce the feature expected from this issue. The expected behaviour is to present a view controller over the current context instead of being in fullscreen. Did I miss something?

**Comment by gabrielPeart** [comment]
@tbaranes You are right. I misread because of the title.

**Comment by gabrielPeart** [comment]
@tbaranes If I understood you correctly what is necessary to do is to create the viewport of the *modal* based on its context's viewport. So in your example, that yellow viewController will be the *context* and its viewport will be used to create and render the modal. This way will achieve what you are looking for.

**Comment by tbaranes** [comment]
Well, I tried that way too, but never find any working solution. If you find it, I'm really interested :D

**Comment by gabrielPeart** [comment]
@tbaranes I'm pretty sure this way will work.
I'm going to implement a simple way to achieve this result and hopefully add it for the next release!

**Comment by tbaranes** [comment]
Looking forward for this release 😬

**Comment by tbaranes** [comment]
@gabrielPeart Did you try to make this working?

**Comment by gabrielPeart** [comment]
@tbaranes not yet. Sorry about that. Have been extremely busy.

**Comment by danlozano** [comment]
@tbaranes @gabrielPeart I think I finally cracked this!

Have been extremely busy lately, but I finally have a couple of days to work solely on open source stuff. This was one of the first things on my to-do list.

@tbaranes Yeah, the "shouldPresentInFullscreen" property of UIPresentationController is of no help, and since in order to get the functionality you need you would need to set the UIModalPresentationStyle to .currentContext or .overCurrentContext, that is not possible because we are using the .custom presentation style.

Therefore this feature needed to be implemented from the ground up. The result looks like so:
```swift
        presenter.viewControllerForContext = self
        presenter.shouldIgnoreTapOutsideContext = true
        customPresentViewController(presenter, viewController: alertController, animated: true, completion: nil)
```

You have to set viewControllerForContext property, in which I use the controllers frame (with some corrections) to set a "context frame", which is hidden from the user. This should ideally be done before a presentation and not in a viewDidLoad because it needs to give a chance to autolayout to have set all frames correctly.

The other optional property is shouldIgnoreTapOutsideContext , the default is false. That means that a tap outside the context frame will be listened to, and will dismiss the presented controller. If this is set to true, then taps on the outside context will be passed along to the other view controller.

This still needs some testing and bug fixing, specially since I had to refactor how animations work to get some of this stuff working hehe, BUT if you checkout the development branch you can checkout the example project to see it in action. Scroll down to the last section where it says "current context" and a split view / container controller situation will show up.

Thanks for your patience! 👍

**Comment by danlozano** [comment]
If any bugs come up we can start a new issue.

**Comment by gabrielPeart** [comment]
@danlozano great work! Thank you!

**Comment by tbaranes** [comment]
Woh, happy to hear that! I will try it this morning, thanks!

**Comment by tbaranes** [comment]
Sorry for the delay, I just test it, it's working as expected, impressive! Thanks for looking into this 👏

**Comment by danlozano** [comment]
Awesome!

Release v 1.2.1 is out.

Had to release a quick .1 bug fix on PresentrShadow.
