### ISSUE TITLE
ViewController doesn't show

### ISSUE THREAD

**Issue by riyanpratama** [IcaliaLabs/Presentr#36]
Hi,

I tried to show my ViewController on my storyboard with 
```
let controller = AsdViewController()
customPresentViewController(presenter, viewController: controller, animated: true, completion: nil)
```
But it just give me blank black transparent screen. I make a sure if my view controller in storyboard has right class. But it still doesn't work. 

Then I try to create ViewController with XIB and it works. My question is, is it support to show view controller on storyboard? Am I missing some step here?

Thank you!

**Comment by danlozano** [comment]
Hi Riyan,

Hmmm I think the issue might be because of this line:

Let controller = AsdViewController()

When instantiating a View Controller from a storyboard you need to do something like this:
Let controller = storyboard.insantiateViewControllerWithIdentifier("asdViewController")

My syntax is probably wrong, but you get the idea :)

**Comment by riyanpratama** [comment]
```
let storyboard = UIStoryboard(name: "MyStoryboard", bundle: nil)
let controller = storyboard.instantiateViewControllerWithIdentifier("asdViewController")
```

It works like a charm. Thank you so much, Danlozano!

**Comment by danlozano** [comment]
YES, you're welcome!

If the _View Controller_ you are currently on is **in** the storyboard, you can just call on the included property on the _View Controller_ self.storyboard , but if you are outside a storyboard you first have to get the storyboard, like you did so in your comment.

Good luck, thanks for using Presentr!
