### ISSUE TITLE
Can't scroll Custom ViewController after version 1.0.1!

### ISSUE THREAD

**Issue by choryuidentify** [IcaliaLabs/Presentr#40]
Hi, I'm using this library make some custom viewcontroller popup, and it's scrollable TableViewController. but it doesn't scrolled when update to 1.0.1. 

I think this problem caused by new added Dismiss on Swipe function, cause I disable dismissOnSwipe option, but it's still can't scrollable... I've downgrade to 1.0.0, It's works good.

Here is my video.
[1.0.0](https://www.youtube.com/watch?v=atkHkxb0HUY)
[1.0.1](https://www.youtube.com/watch?v=q5Wy0QKFQ2E)

**Comment by danlozano** [comment]
Hi @choryuidentify

Thanks so much for the detailed description and videos, that is awesome!

Yeah, the issue is probably due to the new dismissOnSwipe feature. It seems logical that the feature would make scroll views not work properly.

BUT if you disable the dissmissOnSwipe it SHOULD work, I will try to fix this today!

I think the dismissOnSwipe should be disabled by default, and therefore it should not interact with scroll views.

If someone decides to enable dismissOnSwipe, then that means that the user wants this feature and will not use a scroll view.

Thanks again! I will let you know when this is fixed.

**Comment by danlozano** [comment]
@choryuidentify Fixed!

dismissOnSwipe will be by default, false AND if it is false the gesture recognizer will not be added to the view controller, thus preventing any scroll view issues.

If the user wants to activate dismissOnSwipe that is up to them, but they must consider that this will not work properly with a scroll view or subclass(table view, collection view, etc.)

Thanks for using Presentr and for the bug report!

**Comment by choryuidentify** [comment]
Wow! Thanks! It works Perfectly!!

**Comment by danlozano** [comment]
Awesome!
