### ISSUE TITLE
Adapt default AlertViewController height to content body like UIAlertViewController 

### ISSUE THREAD

**Issue by fl0549** [IcaliaLabs/Presentr#50]
Hi, 
I want to know if is possible to size to fit to content body like native UIAlertViewController when presentationType is .alert ?

**Comment by danlozano** [comment]
Hi @fl0549 

Currently that is not possible.

Our included AlertViewController knows nothing about it's presentation, so that class could not have that functionality.

The .alert PresentationType is a fixed size that matches the default Alert in iOS.

As it stands now, if you wanted to do something like that you would have to use a .custom PresentationType and figure out the sizing that your VC will need beforehand, and then present using that .custom PresentationType.

I guess this could be a good feature for the future. We could have an .automatic PresentationType that uses autolayout to figure out it's sizing automatically. Good idea, will definitely look into this.
