### ISSUE TITLE
is there any way to get the callback or copmletion when customPresenter dismissed

### ISSUE THREAD

**Issue by NasrullahKhan** [IcaliaLabs/Presentr#52]
I am using custom presentr controller, i want to do some task after dismiss of presentr. how to know that custom presentr is dismissed?

**Comment by NasrullahKhan** [comment]
@gabrielPeart @edolopez  @kurenn  @mseijas  @thelastinuit  is there any way?

**Comment by danlozano** [comment]
Well there are a couple of ways.

Presentr only automatically dismisses your presented view controller when someone taps on the background. If you want to know when that happens, you have to conform to the 'PresentrDelegate' protocol on the view controller you presented. (You don't have to set any delegate, just conform to the protocol)

Inside that method, you can do anything, then return True so that the VC is dismissed.

```swift
extension ViewController: PresentrDelegate {
    
    func presentrShouldDismiss(keyboardShowing: Bool) -> Bool {
        print("Dismissing View Controller")
        return true
    }
    
}
```

But you could disable dismissOnTap and handle the dismissal of the view controller yourself. Also, if you want to be informed of the dismissal on the view controller you presented from, you probably want to have a custom delegate for the presented view controller, and let the presenting view controller conform to it. But any of that are usual cocoa patterns, so have nothing to do with Presentr.

👍

**Comment by o15a3d4l11s2** [comment]
I have conformed to the protocol and added the method, but it is not being called when I dismiss the view by clicking outside the popup. Is there something that I am doing wrong?

**Comment by MHX792** [comment]
I have the same problem. The method does not get called. Any ideas?
