### ISSUE TITLE
Crash on ios8 (Presentr ver 0.2.1)

### ISSUE THREAD

**Issue by leovu0703vn** [IcaliaLabs/Presentr#55]
I really love your lib and I'm using quite much in my projects. It's running good in all ios version >= 9, however I just got the crash error in ios8 environment. I checked the crash error and saw that the presentingViewController was nil. I tried to fix the pod by myself but I couldn't figure why. Please help me solving this problem. 

![nh ch p man hinh 2016-12-21 luc 18 35 44](https://cloud.githubusercontent.com/assets/20000521/21388174/b305ba0c-c7ad-11e6-90de-9b90a7721983.png)
![nh ch p man hinh 2016-12-21 luc 18 35 52](https://cloud.githubusercontent.com/assets/20000521/21388180/b386e26c-c7ad-11e6-9419-76f959501bc5.png)
![nh ch p man hinh 2016-12-21 luc 18 35 58](https://cloud.githubusercontent.com/assets/20000521/21388179/b37f63fc-c7ad-11e6-8ba2-0c94032a114f.png)
![nh ch p man hinh 2016-12-21 luc 18 36 04](https://cloud.githubusercontent.com/assets/20000521/21388177/b37771ec-c7ad-11e6-80b3-8f4ae9166379.png)
![nh ch p man hinh 2016-12-21 luc 18 36 10](https://cloud.githubusercontent.com/assets/20000521/21388176/b3755d12-c7ad-11e6-85bd-592344d44711.png)
![nh ch p man hinh 2016-12-21 luc 18 36 16](https://cloud.githubusercontent.com/assets/20000521/21388178/b37cc728-c7ad-11e6-93e0-bcfc07830d2a.png)
![nh ch p man hinh 2016-12-21 luc 18 36 25](https://cloud.githubusercontent.com/assets/20000521/21388175/b360e4e0-c7ad-11e6-9616-43faa1cc2f52.png)

**Comment by leovu0703vn** [comment]
*solve 
found out and solve with this code. my ViewController is a XIB file. 

 if #available(iOS 8, *) {
                                        let controllerVC = ViewController(nibName: "ViewController", bundle: nil)
                                        self.customPresentViewController(customPresenter, viewController: controllerVC, animated: true, completion: nil)
                                    } else {
                                        self.customPresentViewController(customPresenter, viewController: controller, animated: true, completion: nil)
                                    }

**Comment by danlozano** [comment]
Hey @leovu0703vn ! 

Hmmm the iOS 8 thing is probably caused because the custom presentation API changed in iOS 10, and now the presentedViewController inside the Presentation controller is now optional, and sometimes is missing.

I will look into that issue. BUT, in the meantime two things.

1.- Your code in the last screenshot seems likely to cause an issue because any Presentr object (in your case the customPresenter) **has** to be a property on your view controller class, it cannot be a local variable like you have in your code. That is because the Presentr object will be the delegate for the transition, so that object needs to live on for the whole presentation.

2.- It confuses me how you solved the issue with your code in the previous comment. What are you doing different inside the **if available ios 8** block? ... The only difference I see is that you are getting the view controller from a nib. But anything Presentr related, i.e. the custom presentation code is the same. Soooo the problem seems to be with the view controller, no?

I appreciate your time trying to get to the bottom of this :) ... I hope we can fix this if there is something wrong.

:)
