### ISSUE TITLE
How to set constraints?

### ISSUE THREAD

**Issue by jadslim313** [IcaliaLabs/Presentr#60]
I have a viewcontroller in storyboard, that I am using as a custom presenter. Im setting constraints for the viewcontroller, but when it shows as a custom popup, all my views are all over the place.. 

I'm not exactly sure how to set proper constraints to make this work, could you please guide me a little,

Thanks!

**Comment by danlozano** [comment]
Hey @jadslim313 !

Well basically with auto-layout the goal is to make a screen work in any size (iphone, plus, ipad, etc.) so Presentr is counting on that so that it does not matter the view controller size it looks "good".

There are some limits to this of course, for example if you present a tiny view controller size where your views do not fit, it will obviously not look good. But generally you should not have this problem.

With auto-layout each view should have a width and height (either by fixed constant contraint, percentage constraint or intrinsic size like in a UILabel) , and each view should have an X and Y position constraint which separates the view from the superview in both axis. This can also be a constant, a percentage, it can be a vertical or horizontal "center" constraint, anything that gives it an x and y position is good.

If you do this for all views in your view controller you should be good. But this applies to any view controller, not just for Presentr. 

For example, you can try viewing your view controller in the Interface Builder in different phone sizes and see how your view constraints react to the changes.

**Comment by danlozano** [comment]
Let me know if you can fix this. Maybe with some sample code.

Thanks for using Presentr :)
