### ISSUE TITLE
Is it possible to dismiss presented controller with some delay?

### ISSUE THREAD

**Issue by parth51** [IcaliaLabs/Presentr#69]
While presenting custom controller its animation works fine. But while dismiss it's so fast that doesn't look like alert dismiss.
I am using below line for dismiss controller

> self.dismiss(animated:true, completion: nil)

**Comment by midgard** [comment]
+1

**Comment by danlozano** [comment]
Ok, let's see. First let's try to debug it.

So you are creating a Presentr object on your presenting view controller, and holding onto it as an instance property correct? That is very important so that the Presentr object remains in memory for the whole present/dismiss.

What did you set for .transitionType and .dismissTransitionType ?

From where are you calling the dismiss? On the presented view controller? Or the presenting?

**Comment by parth51** [comment]
Hi @danlozano         

Yes, I am holding a presentr object in memory.

I set below property for presenting controller.

> presenter.transitionType = .coverVertical
> presenter.presentationType = .fullScreen
> presenter.dismissTransitionType = .coverVertical

I calling dismiss controller from the presented view controller.

**Comment by midgard** [comment]
@danlozano

Presentr like this:
> let presentFromRight: Presentr = {
> let presenter = Presentr(presentationType: .fullScreen);
> presenter.transitionType = .coverHorizontalFromRight;
> presenter.dismissTransitionType = .coverHorizontalFromRight;
> return presenter;
> }();

And I'm calling my login form:
>    let MainStoryBoard = UIStoryboard(name: "Login", bundle: nil);
>    let VC = MainStoryBoard.instantiateViewController(withIdentifier: "LoginVC");
>    customPresentViewController(presentFromRight, viewController: VC, animated: true, completion: nil);

And I'd run "cancel" command on my login form:
> self.dismiss(animated: true, completion: nil);

Presentation is 0.7 or 0.8 seconds
Dismiss is 0.1 or 0.2 secons

**Comment by midgard** [comment]
@parth51 did you found any solution?

**Comment by parth51** [comment]
Nope, I didn't.

**Comment by danlozano** [comment]
Hi! Sorry for the late response, have been really busy with work, but I'm taking this whole week to look over all the issues and PR's. Thanks for your patience!

Let me try your sample code to see if I can recreate and find the bug.

So basically the animation is working, i.e. it's dismissing with the transition type you selected. The problem is the duration of the actual dismissal?

I'm going to try out @midgard 's code , with the cover horizontal transition types.


@parth51 code is also interesting because using these settings
```swift
presenter.transitionType = .coverVertical
presenter.presentationType = .fullScreen
presenter.dismissTransitionType = .coverVertical
```

should not even invoke Presentr because coverVertical is an apple provided transition, the default one, not one of Presentr's custom ones, and .fullScreen is also an apple provided presentation, the default one. So you should not really need Presentr for that exact configuration. BUT if you are also getting the  duration problem with that config. somethings fishy. Let me try this out myself.

:)

**Comment by danlozano** [comment]
Got it!

Realized I was using a UIView animation method which included damping and velocity which was making the presentation and dismissal transitions act in different ways, hence the different speed.

Although this might be useful for someone implementing a custom transition, for now I've just removed that and use the normal UIView animation method which just takes the duration. This has fixed the issue.

Should have a new version out sometime tomorrow or Wednesday with this and other bug fixes and improvements.

Thanks for using Presentr!
