### ISSUE TITLE
Looking for a way to have multiple gesture recognizer

### ISSUE THREAD

**Issue by patthehuman** [IcaliaLabs/Presentr#78]
I have a UITableView controller that I present with Presentr

I turn on swipe to dismiss property, but my tableview can't scroll up and down.

I will take a look at the code and see if it's recognizing gestures simultaneously.

Is there a different workaround for this?

Thx!

**Comment by danlozano** [comment]
Hi @patthehuman 

swipeToDismiss feature is disabled by default because of that problem that it will stop scroll views from working properly.

I believe this can be fixed, probably something to do with this delegate method:

https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate/1624208-gesturerecognizer

Which allows two gesture recognizers to work at same time.

Will look into this on the weekend.
