### ISSUE TITLE
View controller size

### ISSUE THREAD

**Issue by niklassaers** [IcaliaLabs/Presentr#8]
Hi,
.Alert size looks hardcoded, and the others are a factor of the UITransitionView which as far as I understand is the screen size. I have view controllers that I would like to present that use autolayout to become a size, depending on content, text size and dynamic type. I'd love an option to either specify the size of the view controller being presented, that Presentr figures out the size of the presented view controller itself, or that I implement a delegate method where I calculate the view size. Do you have anything for this already, or any guidelines for me to make my changes and submit a PR?

Cheers

   Nik

**Comment by danlozano** [comment]
Hi Nik,

Yes, I decided to hard code the .Alert presentation size since Alert's are usually static no matter what screen they are presented on. I think that's Apple's default behavior if you present an Alert on iPhone or iPad.

And yeah, the other presentation types **do** depend on the screen size, but they are in a way "hard-coded" since they can't be modified by the framework's user.

Presentr being able to figure out the size automatically by using auto-layout would be interesting, but I think that could be a feature for another release. This could work by having a ".Auto" case on the Presentation Type enum. If you would like to work on this (or any other feature) just submit an issue, and then you can fork the project, create a Feature branch on Develop, and send the pull request :)

For now I think I can work on one of your other two ideas. There can be a **Custom** Presentation Type, which allows the framework's user to specify the size and center position, if one of the provided types is not what they need.

This could be done by adding a .Custom case to the **Presentation Type** enum.

This case would have associated values of the enum ModalSize (for the width/height) and ModalCenterPosition enum for the center position. This way if someone want's to set a custom size, but let the calculation for the .Center point up to the framework, or vice-versa.

Then they could just provide this custom Presentation type to Presentr's initializer (or by setting the property) and they could get this custom behavior.

This change could be done pretty quickly because of Presentr's modular design using Enum's. I should be able to get this done today 👍

**Comment by danlozano** [comment]
#4

**Comment by danlozano** [comment]
This other issue deals with the same issue. #4

**Comment by danlozano** [comment]
Done!

You should be able to use a Custom **Presentation Type** in the new [0.1.6](https://github.com/IcaliaLabs/Presentr/releases/tag/0.1.6) release, which should be available via Cocoapods now.

I will update the Readme to provide detailed instructions on how to create a custom presentation, but for now I'll share some example code for creating a 'Top Banner' type alert.

```swift
let customPresenter: Presentr = {
        let width = ModalSize.Full // Can still use Presentr's automatically calculated sizes
        let height = ModalSize.Custom(size: 150) // But can use custom ones when needed
        let center = ModalCenterPosition.CustomOrigin(origin: CGPoint(x: 0, y: 0))
        // let center = ModalCenterPosition.Center // Could also use something like this
        // let center = ModalCenterPosition.Custom(centerPoint: CGPoint(x: 50, y: 50)) // or this
        let customType = PresentationType.Custom(width: width, height: height, center: center)
        
        let customPresenter = Presentr(presentationType: customType)
        customPresenter.transitionType = .CoverVerticalFromTop
        customPresenter.roundCorners = false
        return customPresenter
    }()
```

**Comment by niklassaers** [comment]
Wonderful! :-) Thank! :-) .Custom solves my needs. :-)

**Comment by biagionicp** [comment]
@danlozano how can i change the height of the presented controller after it has been presented? -- such as when the user switches to landscape mode
