### ISSUE TITLE
AlertViewController limited body size

### ISSUE THREAD

**Issue by davidbaez** [IcaliaLabs/Presentr#95]
The body label of the built in AlertViewController cuts off at 3 lines of text. It is a bit limiting. Also the alert size does not grow dynamically depending on the size of the body label, so you have very little padding when you reach the max of 3 lines.

**Comment by danlozano** [comment]
Hey @davidbaez 

Hmmm this is true. Right now the included alert controller is pretty simple. Since I mainly just wanted to use it as an example of how you can present any controller you want with Presentr and make it look and feel like an alert or anything else.

But, as it seems many people are using the alert I will look into improving it on the next release. Ways to make it dynamically grow, change fonts, etc...

You should be able to make a custom presentation and just present it with a larger size. Altough don't know how much the labels will play along.
